apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  labels:
    app: {{ include "prima-tech-challenge.name" . }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::094508075399:role/prima-flask-app-role"