apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prima-tech-challenge.fullname" . }}
  labels:
    app: {{ include "prima-tech-challenge.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prima-tech-challenge.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "prima-tech-challenge.name" . }}
    spec:
      serviceAccountName: flask-app-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DYNAMODB_TABLE
              value: "prima-user-db"
            - name: PYTHONUNBUFFERED
              value: "1"