name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: prima-tech-challenge
  EKS_CLUSTER_NAME: prima-eks-cluster
  # Force all actions to use the updated Node 24 runtime to clear the deprecation warning
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-eks:
    name: Build, Push, and Helm Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          cache: 'pip'           # Speeds up the pipeline by caching dependencies

      - name: Install dependencies
        working-directory: ./app_code  
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # ---------------------------------------------------
      # Run Unit Tests
      # ---------------------------------------------------
      - name: Run Pytest
        working-directory: ./app_code
        run: |
          python -m pytest test_app.py -v        

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::094508075399:role/GitHubActionsEKSRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.0" 

      - name: Terraform Init
        # Point this to whichever folder holds your main.tf
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------------------------------------------
      # 1. Build the Image 
      # ---------------------------------------------------
      - name: Build Docker image
        id: build-image
        working-directory: ./app_code
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # ---------------------------------------------------
      # 2. Container Security Scan 
      # ---------------------------------------------------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # Tell Trivy to scan the image we just built locally
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'                     # Fail the pipeline if vulnerabilities are found
          ignore-unfixed: true               # Ignore vulnerabilities that don't have a patch available yet
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # ---------------------------------------------------
      # Push to ECR
      # ---------------------------------------------------
      - name: Push Docker image to Amazon ECR
        working-directory: ./app_code
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy with Helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          helm upgrade --install prima-tech-challenge-release ./helm/prima-tech-challenge \
            --namespace default \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --wait


  # ---------------------------------------------------
  # Bandit SAST Scanner (Runs in parallel)
  # ---------------------------------------------------
  analyze-code:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install Bandit
        run: pip install bandit
        
      - name: Run Bandit Scan
        working-directory: ./app_code
        # The -r flag scans recursively. 
        # The -lll flag tells it to only fail the pipeline on HIGH severity issues.
        run: bandit -r . -lll